In [1]:
from __future__ import print_function
import torch

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[1.0944e-09, 9.6129e-43, 1.0944e-09],
        [9.6129e-43, 1.0945e-09, 9.6129e-43],
        [1.0945e-09, 9.6129e-43, 1.0947e-09],
        [9.6129e-43, 1.0947e-09, 9.6129e-43],
        [1.0945e-09, 9.6129e-43, 1.0945e-09]])


In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.7715, 0.0175, 0.4039],
        [0.0689, 0.3232, 0.4649],
        [0.0660, 0.4252, 0.9118],
        [0.9737, 0.7925, 0.8079],
        [0.2393, 0.0466, 0.4079]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x=torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[-0.5165,  1.3189,  0.5994],
        [ 1.0867, -0.7198,  0.7977],
        [ 0.2372, -0.5922, -1.7603],
        [-1.2938,  0.4982,  0.2685],
        [-0.7314, -0.9940, -0.7704]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 0.4734,  1.3671,  1.3411],
        [ 1.5504, -0.5695,  1.6799],
        [ 0.9554,  0.1407, -1.0178],
        [-1.1286,  0.6735,  0.2815],
        [-0.5307, -0.9379, -0.1923]])


In [11]:
print(torch.add(x,y))

tensor([[ 0.4734,  1.3671,  1.3411],
        [ 1.5504, -0.5695,  1.6799],
        [ 0.9554,  0.1407, -1.0178],
        [-1.1286,  0.6735,  0.2815],
        [-0.5307, -0.9379, -0.1923]])


In [12]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.4734,  1.3671,  1.3411],
        [ 1.5504, -0.5695,  1.6799],
        [ 0.9554,  0.1407, -1.0178],
        [-1.1286,  0.6735,  0.2815],
        [-0.5307, -0.9379, -0.1923]])


In [13]:
y.add(x)
print(y)

tensor([[0.9899, 0.0481, 0.7416],
        [0.4637, 0.1503, 0.8821],
        [0.7181, 0.7329, 0.7425],
        [0.1652, 0.1754, 0.0130],
        [0.2007, 0.0561, 0.5781]])


In [14]:
print(x[:,1])

tensor([ 1.3189, -0.7198, -0.5922,  0.4982, -0.9940])


In [15]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.1851])
0.18509259819984436


In [ ]:
a=torch.ones(5)
print(a)