In [1]:
import numpy as np
import torch

# f(x)=a*x**2 + b*x + c
x=torch.tensor(0.0,requires_grad=True) # due to gradient on x
a=torch.tensor(1.0)
b=torch.tensor(-2.0)
c=torch.tensor(1.0)
y=a*torch.pow(x,2)+b*x+c

y.backward()
dy_dx=x.grad
print(dy_dx)

tensor(-2.)


In [10]:
import numpy as np
import torch

x=torch.tensor([[0.0,0.0],[1.0,2.0]],requires_grad=True)
a=torch.tensor(1.0)
b=torch.tensor(-2.0)
c=torch.tensor(1.0)
y=a*torch.pow(x,2)+b*x+c

gradient=torch.tensor([[1.0,1.0],[1.0,1.0]])

print("x**2:\n",a*torch.pow(x,2))
print("x*x':\n",torch.matmul(x,x))
print("x:\n",x)
print("y:\n",y)
y.backward(gradient=gradient)
x_grad=x.grad
print("x_grad:\n",x_grad)

x**2:
 tensor([[0., 0.],
        [1., 4.]], grad_fn=<MulBackward0>)
x*x':
 tensor([[0., 0.],
        [2., 4.]], grad_fn=<MmBackward>)
x:
 tensor([[0., 0.],
        [1., 2.]], requires_grad=True)
y:
 tensor([[1., 1.],
        [0., 1.]], grad_fn=<AddBackward0>)
x_grad:
 tensor([[-2., -2.],
        [ 0.,  2.]])
